version: '3'
services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/interview
    links:
      - mongo
    networks:
      - my-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
